apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.thingsboard.storage.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.thingsboard.storage.size }}
