apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
    - port: 9093
      targetPort: 9093
    - port: 9094
      targetPort: 9094
  selector:
    app: kafka
