apiVersion: v1
kind: Service
metadata:
  name: thingsboard
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
    - port: 1883
      targetPort: 1883
    - port: 7070
      targetPort: 7070
    - port: 5683
      targetPort: 5683
  selector:
    app: thingsboard
